/*
 * Gnim JS library Date Picker Component
 *  Version 0.1.1
 *  Write by Ming
 *  Date 2011.10.12
 */
(function(j,p){function n(a,d,c){this.r=!1;this.cb=a;this.f=d;a=document.createElement("div");a.className=q;this.$elm=j(a);this.sel=c=g(c);this.cur=g();this.y=c.y;this.m=c.m;this.refresh()}function g(a){return"string"==typeof a?(a=r.exec(a))?k(a[1],a[2],a[3]):k():a?a:k()}function k(a,d,c){var b=new Date;a!=p&&b.setFullYear(a,d-o,c);return{y:b.getFullYear()+s,m:b.getMonth()+o,d:b.getDate(),w:b.getDay()}}function t(){for(var a="<thead><tr>",d=0;d<h.length;d++)a+="<th>"+h[d]+"</th>";return a+"</tr></thead>"}
function u(a){for(var d=a.cur,c=a.sel,b=a.y,a=a.m,e=k(b,a,1),g=v[a-1]+(2==a&&(0==b%400||0==b%4&&0!=b%100)?1:0),i="<tbody><tr>",h=0,e=1-e.w;;){if(1<=e&&e<=g){var f="";d.y==b&&d.m==a&&d.d==e&&(f+=" "+w);c.y==b&&c.m==a&&c.d==e&&(f+=" "+l);f=j.trim(f);""!=f&&(f=' class="'+f+'"');i+='<td><a href="'+m+'"'+f+">"+e+"</a></td>"}else i+="<td></td>";e++;h++;if(0==h%7&&(e>g||50<e))break;0==h%7&&(i+="</tr><tr>")}return i+"</tr></tbody>"}var q="picker-con",w="picker-today",l="picker-select",m="javascript:void(0);",
v=[31,28,31,30,31,30,31,31,30,31,30,31],h="\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(","),s=0,o=1,r=/^(\d*)-(\d*)-(\d*)$/;n.prototype={refresh:function(){var a=this,d=a.$elm,c=j('<div class="picker-title"><a class="picker-title-prev" href="'+m+'">\u4e0a\u6708</a><a class="picker-title-next" href="'+m+'">\u4e0b\u6708</a><div class="picker-title-text"><em>'+a.y+"</em> \u5e74 <em>"+a.m+"</em> \u6708</div></div>");c.find(".picker-title-prev").click(function(){0>=--a.m&&(a.m=12,--a.y);a.refresh()});
c.find(".picker-title-next").click(function(){13<=++a.m&&(a.m=1,++a.y);a.refresh()});var b='<div class="picker-content"><table>'+t()+u(a)+"</table></div>",b=j(b);b.find("a").click(function(b){b=b.srcElement||b.target;a.$elm.find(".picker-content a").removeClass(l);b=j(b).addClass(l).html();a.sel=k(a.y,a.m,b);a.cb&&a.cb(a.get())});d.empty().append(c).append(b)},appendTo:function(a){this.$elm.appendTo(a);return this},get:function(){return this.f?this.f.replace("yyyy",this.sel.y).replace("mm",(10<=this.sel.m?
"":"0")+this.sel.m).replace("dd",(10<=this.sel.d?"":"0")+this.sel.d).replace("yy",(10<=this.sel.y%100?"":"0")+this.sel.y%100).replace("m",this.sel.m).replace("d",this.sel.d).replace("ww","\u661f\u671f"+h[this.sel.w]):this.sel},set:function(a){this.sel=a=g(a);return this},show:function(a){a=a?g(a):this.get();this.y=a.y;this.m=a.m;this.refresh();return this},remove:function(){this.r||(this.$elm.remove(),this.r=!0);return this},noBubble:function(){this.$elm.click(function(a){j.noBubble(a)});return this}};
window.Datepicker=n})(Gnim);
