/*
 * Gnim JS library Date Picker Component
 *  Version 0.2.0
 *  Write by Ming
 *  Date 2014.01.23
 */
(function(g,s,y){function h(b,a,c){b=g(document.createElement(b));a&&b.addClass(a);c&&b.appendTo(c);return b}function m(b,a,c,d){b=g('<a href="javascript:;"></a>').text(b).click(a);c&&b.appendTo(c);d&&b.addClass(d);return b}function f(b,a){for(var c=a||2,d="";0<c;)d+="0",c--;d+=b;return d.substr(d.length-a,a)}function t(b,a){var c=new Date(b);return a.replace(/yyyy|yy|MM|dd|HH|mm|ss/g,function(a){var b=a.length;switch(a){case "yyyy":case "yy":return f(c.getFullYear(),b);case "MM":return f(c.getMonth()+
1,b);case "dd":return f(c.getDate(),b);case "HH":return f(c.getHours(),b);case "mm":return f(c.getMinutes(),b);case "ss":return f(c.getSeconds(),b);default:return a}})}function l(b){var a=[];b.replace(/(\d+)/g,function(b){a.push(parseInt(b.replace(/^0+/,"")||0))});b=new Date;b.setFullYear(a[0]||1970,a[1]?a[1]-1:0,a[2]||1);b.setHours(a[3]||0,a[4]||0,a[5]||0,a[6]||0);return b.getTime()}function n(b){b=new Date(b);return new Date(b.getFullYear(),b.getMonth(),b.getDate())}function p(b,a){var c=n(b),d=
s;return(d=a?11===c.getMonth()?new Date(c.getFullYear()+1,0,1):new Date(c.getFullYear(),c.getMonth()+1,1):0===c.getMonth()?new Date(c.getFullYear()-1,11,1):new Date(c.getFullYear(),c.getMonth()-1,1))?d.getTime():0}function u(b,a){return Math.ceil((n(b).getTime()-n(a).getTime())/864E5)}function k(b,a,c){var d=this;d.removed=!1;d.cb=b;d.format=a;a=d.$dom=h("div",z,void 0);var e=h("div",A,a);m("\u4e0a\u6708",function(){d.refresh(p(d.cur,!1))},e,B);m("\u4e0b\u6708",function(){d.refresh(p(d.cur,!0))},
e,C);h("div",v,e);D(a);var f=h("div",E,a);for(a=0;a<w.length;a++)(function(a,c,e){m(a,function(){var a=g.now()+q*c;d.set(a,!0);b&&b(e?"":d.get())},f,F)})(w[a],2<a?0:a,2<a);d.set(c,!0)}function D(b){for(var a="<table><thead><tr>",c=0;c<x.length;c++)a+="<th>"+x[c]+"</th>";a+="</tr></thead><tbody>";for(c=0;6>c;c++){for(var a=a+"<tr>",d=0;7>d;d++)a+="<td></td>";a+="</tr>"}a+="</tbody></table>";h("div",G,b).html(a)}var z="picker-con",A="picker-title",B="picker-title-prev",C="picker-title-next",v="picker-title-text",
G="picker-content",E="picker-buttons",F="picker-button",x="\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split(""),w=["\u4eca\u5929","\u660e\u5929","\u540e\u5929","\u6e05\u9664"],q=864E5;k.formatDate=t;k.parseDate=l;k.prototype={get:function(){return this.format?t(this.ts,this.format):this.ts},set:function(b,a){var c=b||g.now();this.ts=c?g.isNum(c)?c:g.isStr(c)?l(c):l(c.year+"-"+c.month+"-"+c.date):g.now();this.refresh(a?this.ts:y);return this},refresh:function(b){var a=this;b&&(a.cur=b);b=n(a.cur);
var c=new Date(b.getFullYear(),b.getMonth(),1);b=(new Date(p(a.cur,!0)-q)).getDate();var d=a.$dom;d.find("."+v).html("<em>"+c.getFullYear()+"</em> \u5e74 <em>"+(c.getMonth()+1)+"</em> \u6708");for(var e=d.find("tbody tr").addClass("picker-hide"),f=d.find("tbody td").empty().removeClass("picker-today").removeClass("picker-select"),h=c.getDay(),k=u(a.ts,c.getTime()),l=u(g.now(),c.getTime()),d=Math.ceil((h+b)/7),r=0;r<d;r++)g(e[r]).removeClass("picker-hide");for(e=0;e<b;e++)(function(b){var d=m((b+1).toString(),
function(){var d=c.getTime()+b*q;a.set(d,!0);a.cb&&a.cb(a.get())},f[h+b]);b===k&&d.addClass("picker-select");b===l&&d.addClass("picker-today")})(e)},appendTo:function(b){this.$dom.appendTo(b);return this},remove:function(){this.removed||(this.$dom.remove(),this.$dom=s,this.removed=!0);return this}};window.Datepicker=k})(Gnim,null);
